app:
  stefan:
    notebook: /stefan/notebook
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ostap.shevchenko.con@gmail.com
    password: andrii2019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true