api:
  stefan:
      notebook: api/stefan/notebook
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ostap.shevchenko.con@gmail.com
    password: andrii2019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:testdb
    password: sa
    username: sa
    driver-class-name: org.h2.Driver