INSERT INTO PRODUCT (BRAND,MODEL) VALUES ('lENOVO','A1') ;
INSERT INTO PRODUCT (BRAND,MODEL) VALUES ('HP','A4') ;
INSERT INTO PRODUCT (BRAND,MODEL) VALUES ('ACER','A3') ;
INSERT INTO PRODUCT (BRAND,MODEL) VALUES ('DELL','A2') ;